#!/bin/bash
set -e

# ==========================================
# Configuration
# ==========================================
PROJECT_NAME="crowd-monitoring"
ENVIRONMENT="dev"
REGION="eu-west-2"
WAF_REGION="us-east-1"
S3_BUCKET_ARTIFACTS="${PROJECT_NAME}-cfn-artifacts-${ENVIRONMENT}"

echo "✥ CrowdSync CloudFormation Deployment Script ✥"

# ==========================================
# 1. Create S3 Bucket for SAM Artifacts
# ==========================================
echo "→ Checking artifact bucket: $S3_BUCKET_ARTIFACTS"
if ! aws s3api head-bucket --bucket "$S3_BUCKET_ARTIFACTS" --region "$REGION" 2>/dev/null; then
    echo "Creating artifact bucket..."
    aws s3 mb s3://$S3_BUCKET_ARTIFACTS --region $REGION
fi

# ==========================================
# 2. Deploy Global WAF (us-east-1)
# ==========================================
echo "→ Deploying Global WAF Stack in $WAF_REGION"
WAF_STACK_NAME="${PROJECT_NAME}-waf-${ENVIRONMENT}"
aws cloudformation deploy \
    --template-file waf-global.yaml \
    --stack-name $WAF_STACK_NAME \
    --region $WAF_REGION \
    --parameter-overrides ProjectName=$PROJECT_NAME Environment=$ENVIRONMENT \
    --no-fail-on-empty-changeset

# Get the WAF ARN
WAF_ARN=$(aws cloudformation describe-stacks \
    --stack-name $WAF_STACK_NAME \
    --region $WAF_REGION \
    --query "Stacks[0].Outputs[?OutputKey=='WebAclArn'].OutputValue" \
    --output text)
echo "Global WAF ARN: $WAF_ARN"

# ==========================================
# 3. Package and Deploy Main Infrastructure
# ==========================================
echo "→ Building and Packaging Main Template via SAM..."
MAIN_STACK_NAME="${PROJECT_NAME}-main-${ENVIRONMENT}"

sam build --template-file template.yaml

sam package \
    --output-template-file packaged.yaml \
    --s3-bucket $S3_BUCKET_ARTIFACTS \
    --region $REGION

echo "→ Deploying Main Infrastructure in $REGION"
sam deploy \
    --template-file packaged.yaml \
    --stack-name $MAIN_STACK_NAME \
    --region $REGION \
    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
    --parameter-overrides \
        ProjectName=$PROJECT_NAME \
        Environment=$ENVIRONMENT

# ==========================================
# 4. Deploy Frontend
# ==========================================
echo "→ Extracting outputs..."
FRONTEND_BUCKET=$(aws cloudformation describe-stack-resources --stack-name $MAIN_STACK_NAME --region $REGION --query "StackResources[?LogicalResourceId=='FrontendBucket'].PhysicalResourceId" --output text)
USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name $MAIN_STACK_NAME --region $REGION --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text)
CLIENT_ID=$(aws cloudformation describe-stacks --stack-name $MAIN_STACK_NAME --region $REGION --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" --output text)
API_URL=$(aws cloudformation describe-stacks --stack-name $MAIN_STACK_NAME --region $REGION --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)
APPSYNC_URL=$(aws cloudformation describe-stacks --stack-name $MAIN_STACK_NAME --region $REGION --query "Stacks[0].Outputs[?OutputKey=='AppSyncUrl'].OutputValue" --output text)

echo "→ Updating React aws-config.ts..."
cat <<EOF > ../dashboard/src/aws-config.ts
// Auto-generated by deploy.sh
const awsConfig = {
    Auth: {
        region: '${REGION}',
        userPoolId: '${USER_POOL_ID}',
        userPoolWebClientId: '${CLIENT_ID}',
    },
    API: {
        endpoints: [
            {
                name: 'CrowdMonitorAPI',
                endpoint: '${API_URL}',
                region: '${REGION}',
            }
        ]
    },
    aws_appsync_graphqlEndpoint: '${APPSYNC_URL}',
    aws_appsync_region: '${REGION}',
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
}

export default awsConfig;
EOF

echo "→ Building Frontend..."
cd ../dashboard
npm install
npm run build

echo "→ Syncing Frontend to S3 ($FRONTEND_BUCKET)..."
aws s3 sync dist/ s3://$FRONTEND_BUCKET --delete

echo "✥ Deployment Complete ✥"
