AWSTemplateFormatVersion: '2010-09-09'
Description: CrowdSync Regional WAF for API Gateway (Deployed in eu-west-2)

Parameters:
  ProjectName:
    Type: String
    Default: crowd-monitoring
  Environment:
    Type: String
    Default: dev

Resources:
  RegionalWafAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${ProjectName}-regional-waf-${Environment}"
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${ProjectName}-regional-waf"
        SampledRequestsEnabled: true
      Rules:
        - Name: BlockHackerWord
          Priority: 0
          Statement:
            ByteMatchStatement:
              FieldToMatch:
                Body: {}
              PositionalConstraint: CONTAINS
              SearchString: "HACKER"
              TextTransformations:
                - Priority: 0
                  Type: LOWERCASE
          Action:
            Block: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "BlockHackerWord"
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "AWSManagedRulesCommonRuleSet"
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "AWSManagedRulesAmazonIpReputationList"
            SampledRequestsEnabled: true

Outputs:
  WebAclArn:
    Description: ARN of the Regional WAF
    Value: !GetAtt RegionalWafAcl.Arn
