// Auto-generated by scripts/manage.py — do not edit manually
const awsConfig = {
    Auth: {
        region: 'eu-west-2',
        userPoolId: 'eu-west-2_jVSoCkiFx',
        userPoolWebClientId: '1pq4qqusm4rr0u9vn0b53t3a8g',
    },
    API: {
        endpoints: [
            {
                name: 'CrowdMonitorAPI',
                endpoint: 'https://xxgad8h2n9.execute-api.eu-west-2.amazonaws.com',
                region: 'eu-west-2',
            }
        ]
    },
    aws_appsync_graphqlEndpoint: 'https://fijvczg5fvhrtlxqimguikto4q.appsync-api.eu-west-2.amazonaws.com/graphql',
    aws_appsync_region: 'eu-west-2',
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
}

export default awsConfig;
