// This file is auto-generated by scripts/manage.py on every deploy.
// Do NOT edit manually — your changes will be overwritten.
//
// To regenerate with live values: python3 scripts/manage.py up
//
// For local development, copy this file to aws-config.ts and fill in
// the values from: python3 scripts/manage.py status

const awsConfig = {
    Auth: {
        region: 'eu-west-2',
        userPoolId: 'eu-west-2_XXXXXXXXX',
        userPoolWebClientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
    API: {
        endpoints: [
            {
                name: 'CrowdMonitorAPI',
                endpoint: 'https://XXXXXXXXXX.execute-api.eu-west-2.amazonaws.com',
                region: 'eu-west-2',
            }
        ]
    }
}

export default awsConfig;
